@startuml ComponentDiagram
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Component Diagram v0.2

Container(userUI, "User UI", "ReactJS - Microservice", "Single Page App")
ContainerDb(authDb, "Database", "PostgreSQL", "Store authentication service data in auth schema")
Container(kafka,"Distributed Event Streaming Platform", "Apache Kafka","Handle event-based communication between microservices")

Container_Boundary(auth-service, "Authentication Service"){
  Container(auth_http_adapter , "HTTP Adapter", "fiber", "Handle HTTP request (parsing, validation) and response")
  Container(auth_db_adapter , "Database Adapter", "go-gorm", "Provide methods to interact with auth database")
  Container(auth_event_producer_adapter , "Event Producer Adapter", "kafka-go", "Publish auth events to other services")
  Container(auth_usecase, "Usecase", "struct with methods implementing business logic")
  Container(auth_entity, "Entity", "struct", "Define db models and http request-response structure; used by all layers")
  Container(auth_logging_adapter, "Logging Adapter", "zerolog", "Log info, error, debug logs; used by all layers")

  Rel(auth_http_adapter, auth_usecase, "Uses")
  Rel(auth_usecase, auth_db_adapter, "Uses")
  Rel(auth_usecase, auth_event_producer_adapter, "Uses")
}

Rel(userUI, auth_http_adapter, "Make API calls", "REST/HTTPS")
Rel(auth_db_adapter, authDb, "Uses")
Rel(auth_event_producer_adapter, kafka, "Publish")

SHOW_LEGEND()
@enduml